### ISSUE TITLE
Questions about preprocessing data, [RoBERTa model]

### ISSUE THREAD

**Issue by spurscoder** [grammarly/gector#15]
Hi,

I found that when preprocessing data for RoBERTa model, there is a difference between our code and the official code of RoBERTa model

### **Our code's preprocessing procedure is:**
1. [Split the sentence by `space` to tokens](https://github.com/grammarly/gector/blob/master/predict.py#L13)
2. [BPE every tokens](https://github.com/grammarly/gector/blob/master/gector/gec_model.py#L207)

### **The official code's preprocessing procedure is:**
1. [Split the sentence by `self.pat` to tokens](https://github.com/pytorch/fairseq/blob/master/fairseq/data/encoders/gpt2_bpe_utils.py#L106)
2. [BPE every tokens](https://github.com/pytorch/fairseq/blob/master/fairseq/data/encoders/gpt2_bpe_utils.py#L106-L110)

### **The Main difference is: _How to segment a sentence_**
For example (Just forget the token `$START`)：
```
1.original sentence is: "That is impossible ."
2.our code's BPE results: "[1711, 354, 11850, 31497, 4]", which is "['That', 'is', 'imp', 'ossible', '.']", before encoding it.
3.official code's BPE results: "[1711, 16, 4703, 479]", which is "['That', 'Ġis', 'Ġimpossible', 'Ġ.']", before encoding it. 'Ġ' is byte_encoded from space.
```
### So I think this difference will affect the RoBERTa model's performance.
Could you give me some explanation? Thank you.

**Comment by komelianchuk** [comment]
Yes, you are right this difference is present and hurt results a bit.
We first split sentences by spaces into tokens, then tokenized each token separately. This was done mainly because of the necessity to have "token to bpe" mapping. We use only the first bpe piece of each token during the linear projection stage for getting tags. (number of tags should match the number of word tokens)

In recent transformers versions, you can encode the whole sentence, get offsets (with encode_plus method) and then calculate this mapping in a different way. But it requires refactoring of the code and retraining the model.

**Comment by spurscoder** [comment]
Yes,

**Comment by spurscoder** [comment]
Yes, this is important. (number of tags should match the number of word tokens)

**Comment by spurscoder** [comment]
Yes, this is important. (number of tags should match the number of word tokens)

**Comment by spurscoder** [comment]
Yes, this is important. (number of tags should match the number of word tokens)

Maybe, when we split the sentence. 
we can use the official code and change the original [self.pat](https://github.com/pytorch/fairseq/blob/master/fairseq/data/encoders/gpt2_bpe_utils.py#L63) to 
```
self.pat = self.re.compile(r""" ?\S+""")   # only split by space and keep the space
```
