### ISSUE TITLE
Tokenization problem

### ISSUE THREAD

**Issue by tr-andrew** [grammarly/gector#48]
Thanks for the tool and models, the accuracy is pretty impressive! One thing I did notice was that the way the input was split into tokens causes some problems. [predict.py is using python's string.split()](https://github.com/grammarly/gector/blob/86a310bee4aa470690f631b80dec832cdecb707a/predict.py#L13) to get an array of tokens, but string.split() doesn't separate punctuation from a word.

This causes things like this.
Original:
> We need to be aware of cultural difference.

Corrected:
> We need to be aware of cultural difference.sssss

or

Original:
> I like to think about problems and ways to solve.

Corrected:
> I like to think about problems and ways to solve. them

I changed the string.split() to spaCy's tokenizer to get the array of tokens and it's working much better.
Original:
> We need to be aware of cultural difference.

Corrected:
> We need to be aware of cultural differences .

or

Original:
> I like to think about problems and ways to solve.

Corrected:
> I like to think about problems and ways to solve them .

Of course, loading spaCy's model reduces speed (that's why I didn't submit a PR), so maybe there's a better option for tokenization. Just wanted to share the problem with string.split().

**Comment by skurzhanskyi** [comment]
Hey @tr-andrew 
Here we should be accurate with the terms. There are two types of tokenizations: general tokenization (e.g., with spaCy) and subword tokenization (model specific). They both should be done before the inference.
It's assumed that general tokenization is already performed (as it was applied for both train and test [data](https://www.cl.cam.ac.uk/research/nl/bea2019st/#data)). That's why it's not part of our pipeline.
Subword tokenization is applied under the hood (in the `handle_batch` method).
