### ISSUE TITLE
Is there a tokenizer problem when using pretrained RoBerta?

### ISSUE THREAD

**Issue by JesseWong333** [grammarly/gector#50]
Thank for sharing your excellent work.

The RoBerta model uses a Byte level BPE, and the vocabulary loaded from pretrained RoBerta looks like this,
![image](https://user-images.githubusercontent.com/38905979/90086673-8b72d380-dd4d-11ea-8947-755175dbec80.png)

Note that there is a special unicode character 'Ġ' before token 'the',  and  'Ġ'  means a blank space .
For example, 'Ġthe' is indexed as 5 in the vocabulary, and 'the' is indexed as 627.

But when processing the data, all the lines are simplely using 'split()' methods, which leads to that the word 'the' is encoded as 627 instead of 5.

So,  I reckon there are lots of tokens that are not indexed correctly.  Although, the stage one pre-training cound alleviate this problems.

**Comment by komelianchuk** [comment]
Yes, you are right. We indeed used incorrect tokenization due to the necessity to have "token to bpe" mapping as was mentioned in #15.
In recent transformer versions, it is possible to use fastTokenzers (but not for XLNet) which provide you offsets for free, but for reproducibility reasons, we decide to stay with this implementation.
