### ISSUE TITLE
Low iteration speed

### ISSUE THREAD

**Issue by Jason3900** [grammarly/gector#7]
Hi!
There's a problem occured when I tried to pretrain the model on mutliple(8) GPUs. It seems that the utility of per GPU is low (10%), and the iteration speed is only about 8s/it. Is there something wrong with my configuration?
By the way, when I use pytorch 1.3.0, it always return a Segmentation fault. So I upgrade the pytorch to ver. 1.5.0, and it disappears. But it didn't work out of "Stop Iteration" as mentioned in https://github.com/huggingface/transformers/issues/4189 . So I followed the advice and install the transformers 2.10.0 from source. Is there something related to the low iteration speed problem?
The GPU devices I use are Nvidia GTX 1080Ti.

**Comment by komelianchuk** [comment]
Hi, @Jason3900 
We conducted the majority of our experiments on single GPUs, but it's also possible to use multiple GPUs setup.
It's true that there are some issues with old versions of torch/transformers and data parallelism.
However, with recent versions, it should be feasible to run the training on multiple GPUs.
One important notice: you need to set batch size N times smaller (where N is a number of GPUs) in order to do updates on the same amount of data. We've tested training on 4 GPUs with this trick and training time was approx 2.5-3 times better compared to single GPU setup.

**Comment by Jason3900** [comment]
@komelianchuk 
Thanks for your tips! 
I've tried two different ways. The first one is running on a single GPU with 128 (half of your default configuration) batch size. The second one is running on 4 GPU with 64 batch size(the exact amount as yours). Below are the standard output when tranining. It seems that the second strategy is much slower than the first one which uses a single GPU. How does that happen……?
![image](https://user-images.githubusercontent.com/55134225/85912980-6260b700-b863-11ea-9747-4bb082352e18.png)
![image](https://user-images.githubusercontent.com/55134225/85913004-8d4b0b00-b863-11ea-8303-15fec0bddbbd.png)

**Comment by komelianchuk** [comment]
I'm afraid that we forget to mention one important thing regarding the synthetic pertaining step.
You need to set the `updates_per_epoch` parameter equal to 10000. Otherwise, your training time will be crazy.

I think in your example iterations are not equal and it's better to take a look at epoch time with the same number of updates.
In order to reproduce our results I would suggest trying these two setups:
1. Single GPU, batch_size=64, accumulation_size=4, updates_per_epoch=10000 
2. Multi GPU, batch_size=64, accumulation_size=1, updates_per_epoch=10000 

1 update == batch_size  * accumulation_size * n_gpus == 256

**Comment by Jason3900** [comment]
@komelianchuk 
Thanks a lot! I'll follow your advice and try them again.
I do appreciate your reply with so much patience! ^_ ^

**Comment by ashishkumarti** [comment]
sir please help me to solve this error. (also finding it hard to understand how to preprocess the dataset downloaded from https://www.cl.cam.ac.uk/research/nl/bea2019st/#data)
![errorgec](https://user-images.githubusercontent.com/37670459/85957492-68fa4600-b9ab-11ea-9946-da4541fb5bcc.JPG)

**Comment by Jason3900** [comment]
@komelianchuk 
Hey! I think it works. There are two more questions remained.
(1) Do I need to set `updates_per_epoch=10000` for all training stages?
(2) From your description, The real batch size in your paper is actually equal to `batch_size * accumulation_size * n_gpus`? That is to say, If I train on 8 GPU cards and want to re-implement your result, then I need to set the `batch_size=32, accumulation_size=1, n_gpus=8`, which corresponds to the real batch size 256, right?

**Comment by komelianchuk** [comment]
@Jason3900 nice to hear that it works!
1. No, it's needed only for the synthetic pertaining step.
2. Correct.
3. With 1 GPU we spend about 3 days for the synthetic pertaining step. (2 and 3 training steps are much faster). With 4 GPUs training time should be 2-3 times smaller.

**Comment by Jason3900** [comment]
@komelianchuk 
Thanks a lot!

**Comment by kouhonglady** [comment]
How to train on Multi GPU? 
I used  DataParallel ,as the picture.
![image](https://user-images.githubusercontent.com/26353454/92062188-b5f30200-edca-11ea-8ea0-be9fea57c93d.png)
It reported the following error：
![image](https://user-images.githubusercontent.com/26353454/92062113-83490980-edca-11ea-840a-af43d00c035d.png)
